name: flutter_cockpit_workspace

packages:
  - packages/flutter_cockpit_protocol
  - packages/flutter_cockpit
  - packages/cockpit
  - examples/cockpit_demo

scripts:
  analyze:
    run: dart analyze
  test:
    run: >-
      (dart test test) &&
      (cd packages/flutter_cockpit && flutter test) &&
      (cd packages/cockpit && dart test) &&
      (cd examples/cockpit_demo && flutter test)
