name: flutter_cockpit_workspace
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

workspace:
  - packages/flutter_cockpit
  - packages/cockpit
  - examples/cockpit_demo

dev_dependencies:
  cockpit:
    path: packages/cockpit
  lints: ^6.1.0
  melos: 6.3.3
  test: '>=1.25.15 <2.0.0'

flutter:
  uses-material-design: true
