import 'dart:io';

import 'package:path/path.dart' as p;

void main() {
  final packageRoot = p.normalize(p.absolute(Directory.current.path));
  final schemaFile = File(
    p.join(packageRoot, 'schema', 'cockpit.test.v2.schema.json'),
  );
  final outputFile = File(
    p.join(packageRoot, 'lib', 'src', 'schema', 'cockpit_test_v2_schema.dart'),
  );
  final schema = schemaFile.readAsStringSync();
  if (schema.contains("'''")) {
    throw StateError(
      'Schema cannot be embedded in a raw triple-quoted string.',
    );
  }
  outputFile.parent.createSync(recursive: true);
  final output = StringBuffer()
    ..writeln(
      '// Generated by tool/generate_test_schema.dart. Do not edit by hand.',
    )
    ..writeln()
    ..writeln("const String cockpitTestV2SchemaJson = r'''")
    ..write(schema)
    ..writeln("''';");
  outputFile.writeAsStringSync(output.toString());
}
