import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'src/foundation_openapi.dart';
import 'src/foundation_schema.dart';

void main() {
  final packageRoot = p.normalize(p.absolute(Directory.current.path));
  _requirePackageRoot(packageRoot);

  final foundationSchema = _prettyJson(buildFoundationSchema());
  final openApi = _prettyJson(buildFoundationOpenApi());
  final foundationSchemaPath = p.join(
    packageRoot,
    'schema',
    'cockpit.foundation.v2.schema.json',
  );
  final openApiPath = p.join(packageRoot, 'openapi', 'cockpit.v2.openapi.json');
  _write(foundationSchemaPath, foundationSchema);
  _write(openApiPath, openApi);

  final testSchemaPath = p.join(
    packageRoot,
    'schema',
    'cockpit.test.v2.schema.json',
  );
  _writeEmbedded(
    outputPath: p.join(
      packageRoot,
      'lib',
      'src',
      'schema',
      'cockpit_test_v2_schema.dart',
    ),
    constants: <String, String>{
      'cockpitTestV2SchemaJson': File(testSchemaPath).readAsStringSync(),
    },
  );
  _writeEmbedded(
    outputPath: p.join(
      packageRoot,
      'lib',
      'src',
      'schema',
      'cockpit_foundation_v2_contracts.dart',
    ),
    constants: <String, String>{
      'cockpitFoundationV2SchemaJson': foundationSchema,
      'cockpitV2OpenApiJson': openApi,
    },
  );
}

void _requirePackageRoot(String packageRoot) {
  final pubspec = File(p.join(packageRoot, 'pubspec.yaml'));
  if (!pubspec.existsSync() ||
      !pubspec.readAsStringSync().startsWith('name: cockpit_protocol\n')) {
    throw StateError('Run this tool from the cockpit_protocol package root.');
  }
}

String _prettyJson(Map<String, Object?> value) {
  return '${const JsonEncoder.withIndent('  ').convert(value)}\n';
}

void _write(String path, String contents) {
  final file = File(path);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(contents, flush: true);
}

void _writeEmbedded({
  required String outputPath,
  required Map<String, String> constants,
}) {
  final output = StringBuffer()
    ..writeln(
      '// Generated by tool/generate_protocol_contracts.dart. Do not edit.',
    );
  for (final entry in constants.entries) {
    if (entry.value.contains("'''")) {
      throw StateError('${entry.key} cannot be embedded as a raw string.');
    }
    output
      ..writeln()
      ..writeln("const String ${entry.key} = r'''")
      ..write(entry.value)
      ..writeln("''';");
  }
  _write(outputPath, output.toString());
}
