enum CockpitTaskGate {
  sessionReachable,
  targetReachable,
  baselineCollected,
  executionFinished,
  bundleWritten,
  intendedPlaneWorked,
  fallbackAcceptable,
  postconditionsSatisfied,
  artifactsReady,
  logsCollected,
  deliveryReadable,
  deliveryValidated,
  acceptanceEvidenceReadable,
  screenshotReady,
  recordingReadyOrExplained,
  finalAssertionPassed,
}
