// Generated by tool/generate_protocol_contracts.dart. Do not edit.

const String cockpitTestV2SchemaJson = r'''
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/cockpit-dev/flutter_cockpit/packages/cockpit_protocol/schema/cockpit.test.v2.schema.json",
  "title": "Cockpit standalone E2E case",
  "description": "Canonical authored cockpit.test/v2 standalone case document.",
  "$ref": "#/$defs/case",
  "$defs": {
    "nonEmptyString": {
      "type": "string",
      "pattern": "\\S"
    },
    "id": {
      "type": "string",
      "pattern": "^[A-Za-z][A-Za-z0-9._-]{0,127}$"
    },
    "variableReference": {
      "type": "object",
      "properties": {
        "$var": {
          "$ref": "#/$defs/id"
        }
      },
      "required": ["$var"],
      "additionalProperties": false
    },
    "stringTemplate": {
      "oneOf": [
        {
          "$ref": "#/$defs/nonEmptyString"
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "integerTemplate": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "nonNegativeIntegerTemplate": {
      "oneOf": [
        {
          "type": "integer",
          "minimum": 0
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "positiveIntegerTemplate": {
      "oneOf": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "numberTemplate": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "normalizedNumberTemplate": {
      "oneOf": [
        {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "positiveNormalizedNumberTemplate": {
      "oneOf": [
        {
          "type": "number",
          "exclusiveMinimum": 0,
          "maximum": 1
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "booleanTemplate": {
      "oneOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "evidencePolicy": {
      "type": "object",
      "properties": {
        "screenshot": {
          "enum": ["none", "onFailure", "always"]
        },
        "snapshot": {
          "enum": ["none", "onFailure", "always"]
        },
        "failurePolicy": {
          "enum": ["failStep", "recordWarning"]
        }
      },
      "additionalProperties": false
    },
    "safetyDeclaration": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "enum": [
              "externalNavigation",
              "communication",
              "financial",
              "destructive",
              "permissionChange",
              "credentialSensitive"
            ]
          },
          "uniqueItems": true
        },
        "reason": {
          "$ref": "#/$defs/nonEmptyString"
        }
      },
      "required": ["effects"],
      "additionalProperties": false
    },
    "compilerLimits": {
      "type": "object",
      "properties": {
        "maxDocumentBytes": {
          "type": "integer",
          "minimum": 1,
          "maximum": 16777216
        },
        "maxNesting": {
          "type": "integer",
          "minimum": 1,
          "maximum": 64
        },
        "maxExpandedSteps": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100000
        },
        "maxLoopIterations": {
          "type": "integer",
          "minimum": 1,
          "maximum": 10000
        },
        "maxRetryAttempts": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        }
      },
      "additionalProperties": false
    },
    "caseDefaults": {
      "type": "object",
      "properties": {
        "commandTimeoutMs": {
          "type": "integer",
          "minimum": 1,
          "maximum": 3600000
        },
        "cleanupTimeoutMs": {
          "type": "integer",
          "minimum": 1,
          "maximum": 3600000
        },
        "failFast": {
          "type": "boolean"
        },
        "evidence": {
          "$ref": "#/$defs/evidencePolicy"
        },
        "limits": {
          "$ref": "#/$defs/compilerLimits"
        }
      },
      "additionalProperties": false
    },
    "targetRequirements": {
      "type": "object",
      "properties": {
        "platform": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "targetKind": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "plane": {
          "enum": ["semantic", "native", "visual", "coordinate"]
        },
        "appId": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "requiredCapabilities": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          },
          "uniqueItems": true
        }
      },
      "required": ["platform", "targetKind", "plane"],
      "additionalProperties": false
    },
    "variable": {
      "oneOf": [
        {
          "$ref": "#/$defs/stringConstant"
        },
        {
          "$ref": "#/$defs/integerConstant"
        },
        {
          "$ref": "#/$defs/numberConstant"
        },
        {
          "$ref": "#/$defs/booleanConstant"
        },
        {
          "$ref": "#/$defs/jsonConstant"
        },
        {
          "$ref": "#/$defs/stringInput"
        },
        {
          "$ref": "#/$defs/integerInput"
        },
        {
          "$ref": "#/$defs/numberInput"
        },
        {
          "$ref": "#/$defs/booleanInput"
        },
        {
          "$ref": "#/$defs/jsonInput"
        },
        {
          "$ref": "#/$defs/secretVariable"
        }
      ]
    },
    "stringConstant": {
      "$ref": "#/$defs/constantVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "const": "string"
        },
        "value": {
          "$ref": "#/$defs/nonEmptyString"
        }
      }
    },
    "integerConstant": {
      "$ref": "#/$defs/constantVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "const": "integer"
        },
        "value": {
          "type": "integer"
        }
      }
    },
    "numberConstant": {
      "$ref": "#/$defs/constantVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "const": "number"
        },
        "value": {
          "type": "number"
        }
      }
    },
    "booleanConstant": {
      "$ref": "#/$defs/constantVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "const": "boolean"
        },
        "value": {
          "type": "boolean"
        }
      }
    },
    "jsonConstant": {
      "$ref": "#/$defs/constantVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "const": "json"
        },
        "value": true
      }
    },
    "constantVariableBase": {
      "type": "object",
      "properties": {
        "source": {
          "const": "constant"
        },
        "type": {
          "enum": ["string", "integer", "number", "boolean", "json"]
        },
        "value": true
      },
      "required": ["source", "type", "value"]
    },
    "stringInput": {
      "$ref": "#/$defs/inputVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "const": "string"
        },
        "default": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "integerInput": {
      "$ref": "#/$defs/inputVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "const": "integer"
        },
        "default": {
          "type": "integer"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "numberInput": {
      "$ref": "#/$defs/inputVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "const": "number"
        },
        "default": {
          "type": "number"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "booleanInput": {
      "$ref": "#/$defs/inputVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "const": "boolean"
        },
        "default": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "jsonInput": {
      "$ref": "#/$defs/inputVariableBase",
      "unevaluatedProperties": false,
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "const": "json"
        },
        "default": true,
        "required": {
          "type": "boolean"
        }
      }
    },
    "inputVariableBase": {
      "type": "object",
      "properties": {
        "source": {
          "const": "input"
        },
        "type": {
          "enum": ["string", "integer", "number", "boolean", "json"]
        },
        "default": true,
        "required": {
          "type": "boolean"
        }
      },
      "required": ["source", "type"]
    },
    "secretVariable": {
      "type": "object",
      "properties": {
        "source": {
          "const": "secret"
        },
        "type": {
          "const": "string"
        },
        "reference": {
          "$ref": "#/$defs/nonEmptyString"
        }
      },
      "required": ["source", "type", "reference"],
      "additionalProperties": false
    },
    "locator": {
      "oneOf": [
        {
          "$ref": "#/$defs/semanticLocator"
        },
        {
          "$ref": "#/$defs/coordinateLocator"
        },
        {
          "$ref": "#/$defs/visualLocator"
        }
      ]
    },
    "semanticLocator": {
      "type": "object",
      "properties": {
        "strategy": {
          "enum": ["text", "label", "nativeId", "testId", "role", "type", "path"]
        },
        "value": {
          "$ref": "#/$defs/stringTemplate"
        },
        "index": {
          "$ref": "#/$defs/nonNegativeIntegerTemplate"
        },
        "ancestor": {
          "$ref": "#/$defs/locator"
        },
        "fallbacks": {
          "$ref": "#/$defs/locatorList"
        }
      },
      "required": ["strategy", "value"],
      "additionalProperties": false
    },
    "coordinateLocator": {
      "type": "object",
      "properties": {
        "strategy": {
          "const": "coordinate"
        },
        "x": {
          "$ref": "#/$defs/normalizedNumberTemplate"
        },
        "y": {
          "$ref": "#/$defs/normalizedNumberTemplate"
        },
        "index": {
          "$ref": "#/$defs/nonNegativeIntegerTemplate"
        },
        "ancestor": {
          "$ref": "#/$defs/locator"
        },
        "fallbacks": {
          "$ref": "#/$defs/locatorList"
        }
      },
      "required": ["strategy", "x", "y"],
      "additionalProperties": false
    },
    "visualLocator": {
      "type": "object",
      "properties": {
        "strategy": {
          "const": "visual"
        },
        "value": {
          "$ref": "#/$defs/stringTemplate"
        },
        "threshold": {
          "$ref": "#/$defs/positiveNormalizedNumberTemplate"
        },
        "index": {
          "$ref": "#/$defs/nonNegativeIntegerTemplate"
        },
        "ancestor": {
          "$ref": "#/$defs/locator"
        },
        "fallbacks": {
          "$ref": "#/$defs/locatorList"
        }
      },
      "required": ["strategy", "value"],
      "additionalProperties": false
    },
    "locatorList": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/locator"
      }
    },
    "condition": {
      "oneOf": [
        {
          "$ref": "#/$defs/visibleCondition"
        },
        {
          "$ref": "#/$defs/textCondition"
        },
        {
          "$ref": "#/$defs/routeCondition"
        },
        {
          "$ref": "#/$defs/idleCondition"
        }
      ]
    },
    "visibleCondition": {
      "type": "object",
      "properties": {
        "type": {
          "const": "visible"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "expected": {
          "$ref": "#/$defs/booleanTemplate"
        }
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "textCondition": {
      "type": "object",
      "properties": {
        "type": {
          "const": "text"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "text": {
          "$ref": "#/$defs/stringTemplate"
        },
        "matchMode": {
          "enum": ["exact", "contains", "regex"]
        }
      },
      "required": ["type", "locator", "text"],
      "additionalProperties": false
    },
    "routeCondition": {
      "type": "object",
      "properties": {
        "type": {
          "const": "route"
        },
        "route": {
          "$ref": "#/$defs/stringTemplate"
        }
      },
      "required": ["type", "route"],
      "additionalProperties": false
    },
    "idleCondition": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["uiIdle", "networkIdle"]
        },
        "quietMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        }
      },
      "required": ["type"],
      "additionalProperties": false
    },
    "positiveNumberTemplate": {
      "oneOf": [
        {
          "type": "number",
          "exclusiveMinimum": 0
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "selectionIndexTemplate": {
      "oneOf": [
        {
          "type": "integer",
          "minimum": -1
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "activationTemplate": {
      "oneOf": [
        {
          "enum": ["auto", "semantic", "direct", "gesture"]
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "directionTemplate": {
      "oneOf": [
        {
          "enum": ["up", "down", "left", "right"]
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "revealAlignmentTemplate": {
      "oneOf": [
        {
          "enum": ["nearest", "start", "center", "end"]
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "matchModeTemplate": {
      "oneOf": [
        {
          "enum": ["exact", "contains", "regex"]
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "inputActionTemplate": {
      "oneOf": [
        {
          "enum": [
            "none",
            "unspecified",
            "done",
            "go",
            "search",
            "send",
            "next",
            "previous",
            "continueAction",
            "join",
            "route",
            "emergencyCall",
            "newline"
          ]
        },
        {
          "$ref": "#/$defs/variableReference"
        }
      ]
    },
    "keyRequestTemplate": {
      "oneOf": [
        {
          "$ref": "#/$defs/variableReference"
        },
        {
          "type": "object",
          "properties": {
            "logicalKey": {
              "oneOf": [
                {
                  "type": "integer"
                },
                {
                  "$ref": "#/$defs/nonEmptyString"
                }
              ]
            },
            "physicalKey": {
              "oneOf": [
                {
                  "type": "integer"
                },
                {
                  "$ref": "#/$defs/nonEmptyString"
                }
              ]
            },
            "character": {
              "type": "string"
            }
          },
          "required": ["logicalKey"],
          "additionalProperties": false
        }
      ]
    },
    "multiTouchTemplate": {
      "oneOf": [
        {
          "$ref": "#/$defs/variableReference"
        },
        {
          "type": "object",
          "properties": {
            "steps": {
              "type": "array",
              "minItems": 1,
              "maxItems": 32,
              "items": {
                "type": "object",
                "properties": {
                  "pointer": {
                    "type": "integer",
                    "minimum": 0
                  },
                  "phase": {
                    "enum": ["down", "move", "up"]
                  },
                  "atMs": {
                    "type": "integer",
                    "minimum": 0
                  },
                  "dx": {
                    "type": "number"
                  },
                  "dy": {
                    "type": "number"
                  }
                },
                "required": ["pointer", "phase", "atMs", "dx", "dy"],
                "additionalProperties": false
              }
            }
          },
          "required": ["steps"],
          "additionalProperties": false
        }
      ]
    },
    "captureOptionsTemplate": {
      "oneOf": [
        {
          "$ref": "#/$defs/variableReference"
        },
        {
          "type": "object",
          "properties": {
            "reason": {
              "enum": [
                "baseline",
                "before_action",
                "after_action",
                "assertion_failure",
                "acceptance"
              ]
            },
            "includeSnapshot": {
              "type": "boolean"
            },
            "attachToStep": {
              "type": "boolean"
            },
            "profile": {
              "enum": [
                "diagnostic",
                "acceptance",
                "flutterPreferred",
                "nativePreferred"
              ]
            },
            "allowFallback": {
              "type": "boolean"
            },
            "snapshotOptions": {
              "$ref": "#/$defs/snapshotOptions"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "snapshotOptions": {
      "type": "object",
      "properties": {
        "profile": {
          "enum": ["live", "baseline", "investigate", "forensic"]
        },
        "maxTargets": {
          "type": "integer",
          "minimum": 1,
          "maximum": 10000
        },
        "maxAncestorsPerTarget": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "maxPropertiesPerTarget": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "includeStyleDetails": {"type": "boolean"},
        "includeDiagnosticProperties": {"type": "boolean"},
        "emitArtifactWhenLarge": {"type": "boolean"},
        "includeRebuildActivity": {"type": "boolean"},
        "maxRebuildEntries": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "includeNetworkActivity": {"type": "boolean"},
        "maxNetworkEntries": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "networkQuery": {
          "type": "object",
          "properties": {
            "method": {"$ref": "#/$defs/nonEmptyString"},
            "uriContains": {"$ref": "#/$defs/nonEmptyString"},
            "onlyFailures": {"type": "boolean"},
            "statusCodeAtLeast": {
              "type": "integer",
              "minimum": 0,
              "maximum": 999
            }
          },
          "additionalProperties": false
        },
        "includeRuntimeActivity": {"type": "boolean"},
        "maxRuntimeEntries": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        },
        "runtimeQuery": {
          "type": "object",
          "properties": {
            "onlyErrors": {"type": "boolean"},
            "messageContains": {"$ref": "#/$defs/nonEmptyString"}
          },
          "additionalProperties": false
        },
        "includeAccessibilitySummary": {"type": "boolean"},
        "maxAccessibilityEntries": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10000
        }
      },
      "additionalProperties": false
    },
    "snapshotOptionsTemplate": {
      "oneOf": [
        {"$ref": "#/$defs/variableReference"},
        {"$ref": "#/$defs/snapshotOptions"}
      ]
    },
    "action": {
      "oneOf": [
        {
          "$ref": "#/$defs/tapAction"
        },
        {
          "$ref": "#/$defs/longPressAction"
        },
        {
          "$ref": "#/$defs/locatorOnlyAction"
        },
        {
          "$ref": "#/$defs/enterTextAction"
        },
        {
          "$ref": "#/$defs/setTextEditingValueAction"
        },
        {
          "$ref": "#/$defs/sendTextInputActionAction"
        },
        {
          "$ref": "#/$defs/keyEventAction"
        },
        {
          "$ref": "#/$defs/dragAction"
        },
        {
          "$ref": "#/$defs/flingAction"
        },
        {
          "$ref": "#/$defs/swipeAction"
        },
        {
          "$ref": "#/$defs/pinchZoomAction"
        },
        {
          "$ref": "#/$defs/rotateAction"
        },
        {
          "$ref": "#/$defs/panZoomAction"
        },
        {
          "$ref": "#/$defs/multiTouchAction"
        },
        {
          "$ref": "#/$defs/scrollUntilVisibleAction"
        },
        {
          "$ref": "#/$defs/noPayloadAction"
        },
        {
          "$ref": "#/$defs/showOnScreenAction"
        },
        {
          "$ref": "#/$defs/idleAction"
        },
        {
          "$ref": "#/$defs/waitForAction"
        },
        {
          "$ref": "#/$defs/assertVisibleAction"
        },
        {
          "$ref": "#/$defs/assertTextAction"
        },
        {
          "$ref": "#/$defs/captureScreenshotAction"
        },
        {
          "$ref": "#/$defs/collectSnapshotAction"
        }
      ]
    },
    "tapAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "tap"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "activation": {
          "$ref": "#/$defs/activationTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "longPressAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "longPress"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "durationMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "locatorOnlyAction": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["doubleTap", "focusTextInput", "increase", "decrease", "dismiss"]
        },
        "locator": {
          "$ref": "#/$defs/locator"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "enterTextAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "enterText"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "text": {
          "$ref": "#/$defs/stringTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "text"],
      "additionalProperties": false
    },
    "setTextEditingValueAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "setTextEditingValue"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "text": {
          "$ref": "#/$defs/stringTemplate"
        },
        "selectionStart": {
          "$ref": "#/$defs/selectionIndexTemplate"
        },
        "selectionEnd": {
          "$ref": "#/$defs/selectionIndexTemplate"
        },
        "composingStart": {
          "$ref": "#/$defs/selectionIndexTemplate"
        },
        "composingEnd": {
          "$ref": "#/$defs/selectionIndexTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type"],
      "anyOf": [
        {
          "required": ["text"]
        },
        {
          "required": ["selectionStart"]
        },
        {
          "required": ["composingStart"]
        }
      ],
      "dependentRequired": {
        "selectionStart": ["selectionEnd"],
        "selectionEnd": ["selectionStart"],
        "composingStart": ["composingEnd"],
        "composingEnd": ["composingStart"]
      },
      "additionalProperties": false
    },
    "sendTextInputActionAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "sendTextInputAction"
        },
        "inputAction": {
          "$ref": "#/$defs/inputActionTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "inputAction"],
      "additionalProperties": false
    },
    "keyEventAction": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["sendKeyEvent", "sendKeyDownEvent", "sendKeyUpEvent"]
        },
        "keyRequest": {
          "$ref": "#/$defs/keyRequestTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "keyRequest"],
      "additionalProperties": false
    },
    "dragAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "drag"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "dx": {
          "$ref": "#/$defs/numberTemplate"
        },
        "dy": {
          "$ref": "#/$defs/numberTemplate"
        },
        "durationMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "dx", "dy"],
      "not": {
        "properties": {
          "dx": {
            "const": 0
          },
          "dy": {
            "const": 0
          }
        },
        "required": ["dx", "dy"]
      },
      "additionalProperties": false
    },
    "flingAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "fling"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "dx": {
          "$ref": "#/$defs/numberTemplate"
        },
        "dy": {
          "$ref": "#/$defs/numberTemplate"
        },
        "velocity": {
          "$ref": "#/$defs/positiveNumberTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "dx", "dy", "velocity"],
      "not": {
        "properties": {
          "dx": {
            "const": 0
          },
          "dy": {
            "const": 0
          }
        },
        "required": ["dx", "dy"]
      },
      "additionalProperties": false
    },
    "swipeAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "swipe"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "direction": {
          "$ref": "#/$defs/directionTemplate"
        },
        "distance": {
          "$ref": "#/$defs/positiveNormalizedNumberTemplate"
        },
        "durationMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "direction", "distance"],
      "additionalProperties": false
    },
    "pinchZoomAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "pinchZoom"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "scale": {
          "$ref": "#/$defs/positiveNumberTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "scale"],
      "not": {
        "properties": {
          "scale": {
            "const": 1
          }
        },
        "required": ["scale"]
      },
      "additionalProperties": false
    },
    "rotateAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "rotationRadians": {
          "$ref": "#/$defs/numberTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "rotationRadians"],
      "not": {
        "properties": {
          "rotationRadians": {
            "const": 0
          }
        },
        "required": ["rotationRadians"]
      },
      "additionalProperties": false
    },
    "panZoomAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "panZoom"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "panDx": {
          "$ref": "#/$defs/numberTemplate"
        },
        "panDy": {
          "$ref": "#/$defs/numberTemplate"
        },
        "scale": {
          "$ref": "#/$defs/positiveNumberTemplate"
        },
        "rotationRadians": {
          "$ref": "#/$defs/numberTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type"],
      "anyOf": [
        {
          "required": ["panDx"]
        },
        {
          "required": ["panDy"]
        },
        {
          "required": ["scale"]
        },
        {
          "required": ["rotationRadians"]
        }
      ],
      "not": {
        "properties": {
          "panDx": {
            "const": 0
          },
          "panDy": {
            "const": 0
          },
          "scale": {
            "const": 1
          },
          "rotationRadians": {
            "const": 0
          }
        }
      },
      "additionalProperties": false
    },
    "multiTouchAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "multiTouch"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "sequence": {
          "$ref": "#/$defs/multiTouchTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "sequence"],
      "additionalProperties": false
    },
    "scrollUntilVisibleAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "scrollUntilVisible"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "direction": {
          "$ref": "#/$defs/directionTemplate"
        },
        "maxScrolls": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        },
        "durationMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        },
        "revealAlignment": {
          "$ref": "#/$defs/revealAlignmentTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator", "direction"],
      "additionalProperties": false
    },
    "noPayloadAction": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["back", "dismissKeyboard", "clearNetworkActivity"]
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type"],
      "additionalProperties": false
    },
    "showOnScreenAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "showOnScreen"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "revealAlignment": {
          "$ref": "#/$defs/revealAlignmentTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "idleAction": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["waitForNetworkIdle", "waitForUiIdle"]
        },
        "quietMs": {
          "$ref": "#/$defs/positiveIntegerTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type"],
      "additionalProperties": false
    },
    "waitForAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "waitFor"
        },
        "condition": {
          "$ref": "#/$defs/condition"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "condition"],
      "additionalProperties": false
    },
    "assertVisibleAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "assertVisible"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "expected": {
          "$ref": "#/$defs/booleanTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "locator"],
      "additionalProperties": false
    },
    "assertTextAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "assertText"
        },
        "locator": {
          "$ref": "#/$defs/locator"
        },
        "text": {
          "$ref": "#/$defs/stringTemplate"
        },
        "matchMode": {
          "$ref": "#/$defs/matchModeTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "text"],
      "additionalProperties": false
    },
    "captureScreenshotAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "captureScreenshot"
        },
        "artifactName": {
          "$ref": "#/$defs/stringTemplate"
        },
        "captureOptions": {
          "$ref": "#/$defs/captureOptionsTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type", "artifactName"],
      "additionalProperties": false
    },
    "collectSnapshotAction": {
      "type": "object",
      "properties": {
        "type": {
          "const": "collectSnapshot"
        },
        "snapshotOptions": {
          "$ref": "#/$defs/snapshotOptionsTemplate"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["type"],
      "additionalProperties": false
    },
    "step": {
      "type": "object",
      "properties": {
        "stepId": {
          "$ref": "#/$defs/id"
        },
        "description": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "timeoutMs": {
          "type": "integer",
          "minimum": 1,
          "maximum": 3600000
        },
        "evidence": {
          "$ref": "#/$defs/evidencePolicy"
        },
        "safety": {
          "$ref": "#/$defs/safetyDeclaration"
        },
        "action": {
          "$ref": "#/$defs/action"
        },
        "startRecording": {
          "$ref": "#/$defs/startRecordingOperation"
        },
        "stopRecording": {
          "$ref": "#/$defs/stopRecordingOperation"
        },
        "if": {
          "$ref": "#/$defs/ifOperation"
        },
        "retry": {
          "$ref": "#/$defs/retryOperation"
        },
        "loop": {
          "$ref": "#/$defs/loopOperation"
        },
        "call": {
          "$ref": "#/$defs/callOperation"
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["stepId"],
      "oneOf": [
        {
          "required": ["action"]
        },
        {
          "required": ["startRecording"]
        },
        {
          "required": ["stopRecording"]
        },
        {
          "required": ["if"]
        },
        {
          "required": ["retry"]
        },
        {
          "required": ["loop"]
        },
        {
          "required": ["call"]
        }
      ],
      "additionalProperties": false
    },
    "startRecordingOperation": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/$defs/id"
        },
        "purpose": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "mode": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "layer": {
          "enum": ["flutter", "app-window", "host-screen", "system"]
        },
        "allowFallback": {
          "type": "boolean"
        },
        "attachToStep": {
          "type": "boolean"
        }
      },
      "required": ["name"],
      "additionalProperties": false
    },
    "stopRecordingOperation": {
      "type": "object",
      "properties": {
        "settleMs": {
          "type": "integer",
          "minimum": 0,
          "maximum": 60000
        }
      },
      "additionalProperties": false
    },
    "ifOperation": {
      "type": "object",
      "properties": {
        "condition": {
          "$ref": "#/$defs/condition"
        },
        "then": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/step"
          }
        },
        "else": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      },
      "required": ["condition", "then"],
      "anyOf": [
        {
          "properties": {
            "then": {
              "minItems": 1
            }
          }
        },
        {
          "required": ["else"],
          "properties": {
            "else": {
              "minItems": 1
            }
          }
        }
      ],
      "additionalProperties": false
    },
    "retryOperation": {
      "type": "object",
      "properties": {
        "maxAttempts": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "delayMs": {
          "type": "integer",
          "minimum": 0,
          "maximum": 3600000
        },
        "steps": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      },
      "required": ["maxAttempts", "steps"],
      "additionalProperties": false
    },
    "loopOperation": {
      "type": "object",
      "properties": {
        "maxIterations": {
          "type": "integer",
          "minimum": 1,
          "maximum": 10000
        },
        "condition": {
          "$ref": "#/$defs/condition"
        },
        "steps": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      },
      "required": ["maxIterations", "condition", "steps"],
      "additionalProperties": false
    },
    "callOperation": {
      "type": "object",
      "properties": {
        "fragment": {
          "$ref": "#/$defs/id"
        }
      },
      "required": ["fragment"],
      "additionalProperties": false
    },
    "case": {
      "type": "object",
      "properties": {
        "schemaVersion": {
          "const": "cockpit.test/v2"
        },
        "kind": {
          "const": "case"
        },
        "id": {
          "$ref": "#/$defs/id"
        },
        "name": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "description": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          },
          "uniqueItems": true
        },
        "target": {
          "$ref": "#/$defs/targetRequirements"
        },
        "defaults": {
          "$ref": "#/$defs/caseDefaults"
        },
        "variables": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/id"
          },
          "additionalProperties": {
            "$ref": "#/$defs/variable"
          }
        },
        "fragments": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/id"
          },
          "additionalProperties": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/$defs/step"
            }
          }
        },
        "setup": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/step"
          }
        },
        "steps": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/step"
          }
        },
        "finally": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      },
      "patternProperties": {
        "^x-[A-Za-z0-9][A-Za-z0-9._-]*$": true
      },
      "required": ["schemaVersion", "kind", "id", "target", "steps"],
      "additionalProperties": false
    }
  }
}
''';
